version: "3"
services:
  web:
    build: .
    command: flask run
    ports:
      - "5000:5000"
    depends_on: 
      - db
    env_file:
    - .env
  db:
    image: postgres
    env_file:
        - database.env
    ports: 
        - "5432:5432"
    volumes:
        - database-data:/var/lib/postgresql/data
volumes:
    database-data: